name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: docker compose build

      - name: Run tests via reporter
        run: docker compose up --abort-on-container-exit --exit-code-from reporter

      - name: Logs (if something failed)
        if: failure()
        run: |
          docker compose logs --no-color api || true
          docker compose logs --no-color reporter || true

      - name: Cleanup
        if: always()
        run: docker compose down -v --remove-orphans
