name: CI
on:
  push:
  pull_request:

permissions:
  contents: read

env:
  REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DO_PUSH: ${{ github.event_name != 'pull_request' }}

jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ env.DO_PUSH == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build (and push) API
        uses: docker/build-push-action@v6
        with:
          context: ./service-a
          file: ./service-a/Dockerfile
          push: ${{ env.DO_PUSH }}
          tags: |
            ${{ env.REGISTRY_USER }}/cpp-api:latest
            ${{ env.REGISTRY_USER }}/cpp-api:${{ github.sha }}
          provenance: false

  build_reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ env.DO_PUSH == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build (and push) Reporter
        uses: docker/build-push-action@v6
        with:
          context: ./service-b
          file: ./service-b/Dockerfile
          push: ${{ env.DO_PUSH }}
          tags: |
            ${{ env.REGISTRY_USER }}/cpp-reporter:latest
            ${{ env.REGISTRY_USER }}/cpp-reporter:${{ github.sha }}
          provenance: false
